version: '2'
services:
    jhipstersampleapplication2019-app:
        image: jhipstersampleapplication2019
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication2019-mysql:3306/jhipstersampleapplication2019?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://jhipstersampleapplication2019-elasticsearch:9200
        ports:
            - 8080:8080
    jhipstersampleapplication2019-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplication2019-mysql
    jhipstersampleapplication2019-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstersampleapplication2019-elasticsearch
